language: python

services:
  - redis-server

python:
  - "2.6"
  - "2.7"
  - "pypy"

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4

install:
    - pip install Django==$DJANGO
    - python setup.py develop

script:  make test
