language: python

services:
  - redis-server

python:
  - "2.7"
  - "pypy"

env:
  - DJANGO=1.4.22
  - DJANGO=1.7.10
  - DJANGO=1.8.4

install:
    - pip install Django==$DJANGO
    - python setup.py develop

script:  make test
